name: focus_detector_example
description: An example for FocusDetector.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  focus_detector_v2:
    path: ../
  logger: ^1.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  module:
    androidX: false
    androidPackage: com.edsonbueno.focusdetectorexample
    iosBundleIdentifier: com.edsonbueno.focusdetectorexample
