name: focus_detector_example
description: An example for FocusDetector.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  focus_detector:
    path: ../
  logger: ^1.1.0

flutter:
  uses-material-design: true

  module:
    androidX: false
    androidPackage: com.edsonbueno.focusdetectorexample
    iosBundleIdentifier: com.edsonbueno.focusdetectorexample