name: focus_detector_v2
description: Detects when your widget appears or disappears from the screen.
version: 3.1.0+1
homepage: https://github.com/irfnyas/focus_detector

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
