name: focus_detector
description: Detects when your widget appears or disappears from the screen.
version: 2.0.1
homepage: https://github.com/EdsonBueno/focus_detector

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
