name: focus_detector
description: Detects when a widget's visibility changes.
version: 1.1.0
homepage: https://github.com/EdsonBueno/focus_detector

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
