name: focus_detector
description: Android's onResume/onPause and iOS's viewDidAppear/viewDidDisappear for Flutter.
version: 1.0.0
homepage: https://github.com/EdsonBueno/focus_detector

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
