name: focus_detector
description: Wrapper around Google's [VisibilityDetector](https://github.com/google/flutter.widgets/tree/master/packages/visibility_detector) for combining it with Flutter's WidgetsBindingObserver in order to achieve Android's onResume/onPause and iOS's viewDidAppear/viewDidDisappear on Flutter.
version: 1.0.0
homepage: https://edsonbueno.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
