name: focus_detector_v2
description: Detects when your widget appears or disappears from the screen.
version: 3.0.0+2
homepage: https://github.com/irfnyas/focus_detector

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
